version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dicomdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dicom_network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/dicomdb
    command: ["sh", "-c", "sleep 10 && node server.js"] # ✅ Keep this to prevent MySQL startup issues
    networks:
      - dicom_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dicom_network

volumes:
  mysql_data:

networks:
  dicom_network:
    driver: bridge
